# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_id', models.IntegerField()),
                ('item_nickname', models.CharField(max_length=200)),
                ('item_basePrice', models.IntegerField()),
                ('item_isActive', models.BooleanField()),
                ('item_startDate', models.DateField()),
                ('item_endDate', models.DateField()),
                ('item_startTime', models.TimeField()),
                ('item_endTime', models.TimeField()),
            ],
            options={
                'db_table': 'Menu',
                'managed': False,
            },
        ),
    ]
