# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GJ_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=1000)),
                ('QR_code', models.TextField(blank=True)),
                ('is_admin', models.BooleanField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={},
        ),
    ]
