# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 18:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GJ_app', '0002_auto_20160228_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='company_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GJ_app.User'),
        ),
        migrations.AlterModelTable(
            name='menu',
            table=None,
        ),
    ]
